name: C/C++ CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - "Doxyfile"
      - "docs/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.md"
      - "Doxyfile"
      - "docs/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: configure
    #   run: ./configure
    - name: install Valgrind
      run: sudo apt-get install -y valgrind
    - name: make
      run: make DEBUG=1
    - name: make check
      run: make check
    - name: upload coverage
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
